name: desplego automatizador en servidor
run-name: ${{ github.actor }} nuevo tag para automatizador
on: 
  push:
    tags:
      - 'automatizador*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ID_KEY_BELGICA }}" > belgica.pem
      - run: chmod 400 belgica.pem
      - run: scp -r -oStrictHostKeyChecking=no -i "belgica.pem" automatizador/ ${{ secrets.USUARIO_BELGICA }}@${{ secrets.HOST_BELGICA }}:~/automatizador/

