name: desplego en servidor
run-name: ${{ github.actor }} nuevo tag
on: 
  push:
    tags:
      - "*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo "${{ secrets.ID_KEY_HOLANDA }}" > holanda.pem
      - run: chmod 400 holanda.pem
      - run: scp -oStrictHostKeyChecking=no -i "holanda.pem" app.R ${{ secrets.USUARIO_HOLANDA }}@${{ secrets.HOST_HOLANDA }}:~/tablero/app.R

