name: desplego automatizador en servidor
run-name: ${{ github.actor }} nuevo tag para automatizador
on: 
  push:
    tags:
      - automatizador/**
jobs:
  copiando:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ID_KEY_BELGICA }}" > belgica.pem
      - run: chmod 400 belgica.pem
      - run: ssh -oStrictHostKeyChecking=no -i "belgica.pem" ${{ secrets.USUARIO_BELGICA }}@${{ secrets.HOST_BELGICA }} 'rm -f ~/automatizador/*'
      - run: scp -oStrictHostKeyChecking=no -i "belgica.pem" automatizador/*.py ${{ secrets.USUARIO_BELGICA }}@${{ secrets.HOST_BELGICA }}:~/automatizador/

