name: desplego en servidor
run-name: ${{ github.actor }} nuevo tag
on: 
  push:
    tags:
      - "*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo "$ID_KEY_HOLANDA" > holanda.pem
      - run: chmod 400 holanda.pem
      - run: ssh -oStrictHostKeyChecking=no -i "holanda.pem" $usuario_holanda@$host_holanda 'ls -la'

