name: desplego en servidor
run-name: ${{ github.actor }} nuevo tag para front
on: 
  push:
    tags:
      - "front.*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ID_KEY_HOLANDA }}" > holanda.pem
      - run: chmod 400 holanda.pem
      - run: scp -oStrictHostKeyChecking=no -i "holanda.pem" README.md ${{ secrets.USUARIO_HOLANDA }}@${{ secrets.HOST_HOLANDA }}:~/tablero/app.R

